server:
  port: 2222
spring:
  application:
    name: ARTICLE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/articleDb
    username: root
    password: subhanAllah123@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka