server:
  port: 1111
spring:
  application:
    name: VERSION-TRACKING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/policygenerationdb
    username: root
    password: subhanAllah123@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka